### ISSUE TITLE
UrbanXtools

### ISSUE THREAD

**Issue by rewinio82** [CAUPDxUrbanXLab/UrbanXTools#1]

**Comment by alphonse-lin** [comment]
sorry, how can I help you, is it about the Rhino version problem?

**Comment by rewinio82** [comment]
no problem, need sometime to study

**Comment by alphonse-lin** [comment]
Thank you so much for using this tool, please feel free to ask questions or leave any feedback here.

**Comment by michealzhang13** [comment]
I tried to load UrbanXtools several times,but it didnt work. I had used Rhino 6.30, and replied that" An error occured during GHA assembly loading"  : Exception System.IO.FileLoadException:   Message: cant load the file“file:///C:\Users\Administrator\AppData\Roaming\Grasshopper\Libraries\UrbanXTools_v.1.0.0\UrbanXTools.gha” (error from HRESULT:0x80131515).  Exception System.NotSupportedException.

Please give some advice.

Thanks

**Comment by alphonse-lin** [comment]
Did you unblock the GHA file? 
Right-click the gha file, go to properties, you can see the status, don't forget to unblock the GHA.

Thx

**Comment by michealzhang13** [comment]
NOW IT WORK. THANK YOU SO MUCH.

**Comment by MOLLYNN** [comment]
用的6.5不能安装吗？怎么解决？

**Comment by alphonse-lin** [comment]
我们更新了一版基于Rhino6.1的gha，你可以试试看...

**Comment by MOLLYNN** [comment]
> 我们更新了一版基于Rhino6.1的gha，你可以试试看...

谢谢，刚刚试了release6.01可以用

**Comment by sszxlk** [comment]
很棒的一款工具，有个小问题。居住用地，点式住宅设置的进深都是26米，后期有没有可能把建筑的平面尺寸（开间、进深）作为可调参数呢？毕竟在长江中下游地区，这种进深很大的点式住宅在设计实践中已不多见了。

**Comment by alphonse-lin** [comment]
很高兴收到你的反馈，有的，现在已经有这个功能了。可以看Samples->3_UrbanDesign->0_DesignCalculator的示例文件，是可以自己添加样例的。有了自己添加的样例，该电池可以快速得出填充进对应地块的排布个数。

**Comment by alphonse-lin** [comment]
很高兴收到你的反馈，有的，现在这个功能还不是很完善。
目前的功能，可以看Samples->3_UrbanDesign->0_DesignCalculator的示例文件，是可以自己添加样例的。有了自己添加的样例，该电池可以快速得出填充进对应地块的排布个数。
数据内容：可以看UrbanXTools_v.1.0.0->data->UrbanDesign.xml，我们把预设值放在这里了。如果需要改的话，可能得先自己操作一下。

**Comment by alphonse-lin** [comment]
很高兴收到你的反馈，有的，现在这个功能还不是很完善。
- 目前功能：可以看Samples->3_UrbanDesign->0_DesignCalculator的示例文件，是可以自己添加样例的。有了自己添加的样例，该电池可以快速得出填充进对应地块的排布个数。
- 默认数据：可以看UrbanXTools_v.1.0.0->data->UrbanDesign.xml，我们把预设值放在这里了。如果需要改的话，可能得先自己操作一下

很谢谢你的反馈，之后我们会开放出来可以自动调的功能，这样才能更贴近真实的使用模式。

**Comment by beyond888999** [comment]
能不能在youtube更新视频教程呢

**Comment by alphonse-lin** [comment]
好的，我们会尽快在Youtube上更新
