### ISSUE TITLE
关于unlink的疑问

### ISSUE THREAD

**Issue by Alcholatic** [CAUPDxUrbanXLab/UrbanXTools#4]
请问对于轴线或线段模型中的类似高架路等和部分路网没有交叉的连接方式如何体现？可以通过不同高度区分不交叉的位置并且添加上下空间的连接线表示交叉的方式实现吗？

**Comment by alphonse-lin** [comment]
不好意思，回复晚了。最新版本可以直接计算三维路网。在Rhino录入三维空间路网即可。
