### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by polo1968** [CAUPDxUrbanXLab/UrbanXTools#5]
谢谢您的分享，看起来是一个很棒的工具！但是我在grasshopper加载插件的时候显示这个问题，导致无法加载。我的rhino版本是7.4，不知有无解决方法呢？
![微信图片_20220808131033](https://user-images.githubusercontent.com/52640723/183344129-d0ed0c32-e74a-4874-9f18-8a9e8a91656d.jpg)

**Comment by alphonse-lin** [comment]
很谢谢你的提问，之前确实没有碰到Rhino7 的问题，我们会针对这个版本重新发布一次
