### ISSUE TITLE
关于centroidLineExtract这个电池的疑问

### ISSUE THREAD

**Issue by 56V223** [CAUPDxUrbanXLab/UrbanXTools#6]
为什么新版本V3.00中删除了这个电池呢 目前初学GH在城规领域的应用 还不太会自己组装电池提取路网中心线

**Comment by alphonse-lin** [comment]
不好意思，回复晚了。不知道为什么没有email发过来。

我不确定是不是版本下载错了，应该是没有删除的。如果方便的话，我们可以直接聊聊，看看是不是版本的问题。
